version: '3'
services:
  puddings-js:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./workspace/src:/app/workspace/src
    command: /bin/sh -c "while sleep 86400; do :; done" 